name: 'Chromatic Deployment'

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - uses: chromaui/action@v1
        with:
          workingDir: ./packages/ui 
          buildScriptName: "storybook:build"
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.CHROMATIC_GITHUB_TOKEN }}
